/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package probabilidad;

/**
 *
 * @author ulises
 */
public class binomial extends javax.swing.JFrame {

    /**
     * Creates new form binomial
     */
    public binomial() {
        initComponents();
        setLocationRelativeTo(null);
        setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nExitos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nOportunidades = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PExito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        resultadoBinomial = new javax.swing.JTextField();
        salirBinomial = new javax.swing.JButton();
        calcularBinomial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Distribución Binomial");
        setResizable(false);

        jLabel1.setText("Numero de exitos:");

        nExitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nExitosActionPerformed(evt);
            }
        });

        jLabel2.setText("Total de oportunidades:");

        nOportunidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nOportunidadesActionPerformed(evt);
            }
        });

        jLabel3.setText("Probabilidad de exito:");

        PExito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PExitoActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultado:");

        salirBinomial.setText("Salir");
        salirBinomial.setPreferredSize(new java.awt.Dimension(80, 24));
        salirBinomial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBinomialActionPerformed(evt);
            }
        });

        calcularBinomial.setText("Calcular");
        calcularBinomial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularBinomialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(PExito, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(salirBinomial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(calcularBinomial)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nOportunidades, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultadoBinomial, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nExitos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nExitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nOportunidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoBinomial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PExito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirBinomial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcularBinomial))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBinomialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBinomialActionPerformed
        reinicio reinicio1 = new reinicio();
        reinicio1.setVisible(true);
        dispose();
    }//GEN-LAST:event_salirBinomialActionPerformed

    private void nExitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nExitosActionPerformed
            
    }//GEN-LAST:event_nExitosActionPerformed

    private void nOportunidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nOportunidadesActionPerformed
        
    }//GEN-LAST:event_nOportunidadesActionPerformed

    private void calcularBinomialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularBinomialActionPerformed
        double X,N,P,Res,Comb;
        String S = nExitos.getText();
        X = Double.parseDouble(S);
        if(X<=0){
            error error1 = new error();
            error1.setVisible(true);
            nExitos.setText("");
        }
        S = nOportunidades.getText();
        N = Double.parseDouble(S);
        if(N<=0){
            error error1 = new error();
            error1.setVisible(true);
            nOportunidades.setText("");
        }
        S = PExito.getText();
        P = Double.parseDouble(S);
        if(P<=0){
            error error1 = new error();
            error1.setVisible(true);
            PExito.setText("");
        }
        double A = Math.pow(P, N);
        double B=1;
        double D=N;
        while(D!=0){
            B=B*D;
            D--;
        }
        double C=1;
        D=X;
        while(D!=0){
            C=C*D;
            D--;
        }
        D=N-X;
        double F=1;
        while(D!=0){
            F=F*D;
            D--;
        }
        Comb=B/(C*F);
        D=Math.pow(P,X);	
        P=1-P;	
        N=N-X;
        P=Math.pow(P,N);
        D=D*P;
        Res=D*Comb;
        S = Double.toString(Res);
        resultadoBinomial.setText(S);
    }//GEN-LAST:event_calcularBinomialActionPerformed

    private void PExitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PExitoActionPerformed
       
    }//GEN-LAST:event_PExitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(binomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(binomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(binomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(binomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new binomial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PExito;
    private javax.swing.JButton calcularBinomial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nExitos;
    private javax.swing.JTextField nOportunidades;
    private javax.swing.JTextField resultadoBinomial;
    private javax.swing.JButton salirBinomial;
    // End of variables declaration//GEN-END:variables
}
