/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package probabilidad;
import javax.swing.JOptionPane;
import java.lang.Math;
/**
 *
 * @author ulises
 */
public class mediana extends javax.swing.JFrame {

    /**
     * Creates new form mediana
     */
    public mediana() {
        initComponents();
        setLocationRelativeTo(null);
        setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NDMediana = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        resultadoMediana = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        calcularMediana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mediana");
        setResizable(false);

        jLabel1.setText("Numero de datos:");

        jLabel2.setText("Mediana: ");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        calcularMediana.setText("Calcular");
        calcularMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularMedianaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(NDMediana)
                            .addComponent(resultadoMediana, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(calcularMediana)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NDMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultadoMediana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularMediana)
                    .addComponent(cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        reinicio reinicio1 = new reinicio();
        reinicio1.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void calcularMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularMedianaActionPerformed
        String A = NDMediana.getText();
        int J = Integer.parseInt(A);
        int []med = new int[J];
        int temp,i,C,D;
        
        for(i = 0; i<J; i++){
            A=JOptionPane.showInputDialog("ingresa el dato numero "+(i+1)+":");
            if(A.isEmpty()){
                i--;
                continue;
            }
            try{
            temp = Integer.parseInt(A);
            med[i]=temp;
            }
            catch(NumberFormatException e){
                i--;
            }
        }
        for(i=0; i<J-1; i++){
            for(C=0;C<J-i-1;C++){
                if(med[C+1]<med[C]){
                    D = med[C+1];
                    med[C+1]=med[C];
                    med[C]=D;
                }
            }
        }
        float E;
        E=J%2;
        if(E!=0){
            E=J/2;
            Math.ceil(E);
            D=(int)E;
            resultadoMediana.setText(""+med[D]);
            NDMediana.setText("");
        }
        else{
            E=J/2;
            Math.ceil(E);
            D=(int)E;
            if(med[D]==med[D-1]){
                resultadoMediana.setText(""+med[D]);
                NDMediana.setText("");
            }
            else if(med[D]!=med[D-1]){
                resultadoMediana.setText("Tiene dos valores "+med[D]+" y "+med[D-1]);
                NDMediana.setText("");
            }
        }
    }//GEN-LAST:event_calcularMedianaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mediana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mediana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NDMediana;
    private javax.swing.JButton calcularMediana;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField resultadoMediana;
    // End of variables declaration//GEN-END:variables
}
